easy_words = [
    "cat", "dog", "hat", "sun", "fish",
    "book", "tree", "cake", "bird", "moon",
    "apple", "ball", "car", "duck", "egg",
    "frog", "goat", "hat", "ice", "jam",
    "kite", "lamp", "mouse", "nose", "owl",
    "pig", "queen", "rat", "sock", "tree",
    "umbrella", "van", "whale", "box", "yarn",
    "zebra", "ant", "bat", "cup", "doll",
    "elf", "fan", "girl", "hill", "ink",
    "jar", "key", "leaf", "milk", "nest",
    "orange", "pen", "quilt", "ring", "star",
    "train", "unicorn", "vase", "water", "xray",
    "yoyo", "zip", "apple", "baby", "cat",
    "door", "egg", "fire", "goose", "horse",
    "igloo", "jelly", "king", "lion", "mango",
    "nut", "octopus", "pie", "queen", "rope",
    "ship", "toy", "unicorn", "vase", "whale",
    "xray", "yacht", "zoo", "ape", "bell",
    "cake", "drum", "ear", "frog", "gate"
]

medium_words = [
    "guitar", "computer", "elephant", "butterfly", "umbrella",
    "piano", "tiger", "keyboard", "telephone", "octopus",
    "television", "bicycle", "dragon", "camera", "crocodile",
    "banana", "caterpillar", "astronaut", "fireworks", "helicopter",
    "mosquito", "astronomy", "dictionary", "elephant", "explosion",
    "hospital", "mountain", "restaurant", "volcano", "waterfall",
    "broccoli", "cinnamon", "dolphin", "envelope", "fireplace",
    "giraffe", "hamburger", "kangaroo", "lighthouse", "motorcycle",
    "penguin", "pineapple", "sandwich", "scorpion", "snowflake",
    "sunflower", "telephone", "thunderstorm", "umbrella", "violin",
    "whistle", "xylophone", "yogurt", "zeppelin", "accordion",
    "backpack", "chameleon", "compass", "elephant", "geography",
    "hedgehog", "mountain", "pajamas", "paintbrush", "quicksand",
    "skyscraper", "submarine", "sweater", "telephone", "treasure",
    "violin", "volcano", "wristwatch", "xylophone", "yacht",
    "zucchini", "asparagus", "astronaut", "backpack", "butterfly",
    "caterpillar", "dinosaur", "electricity", "firefighter", "guitar",
    "hurricane", "jellyfish", "kangaroo", "laboratory", "mushroom",
    "nightingale", "octopus", "penguin", "quicksilver", "raccoon"
]

hard_words = [
    "xylophone", "quizzical", "rhythm", "juxtaposition", "zephyr",
    "mnemonic", "cryptocurrency", "jacuzzi", "schizophrenia", "vexatious",
    "gazebo", "chiaroscuro", "juggernaut", "onomatopoeia", "xenophobia",
    "bouillabaisse", "pseudonym", "sphygmomanometer", "synecdoche", "euphemism",
    "glockenspiel", "kaleidoscope", "acquiesce", "phlegmatic", "sesquipedalian",
    "ubiquitous", "idiosyncrasy", "myrmecologist", "quixotic", "vichyssoise",
    "weltschmerz", "xenomorph", "zeugma", "verisimilitude", "tyrannosaurus",
    "quadruped", "juxtapose", "xylography", "quadrilateral", "ziggurat",
    "nefarious", "obsequious", "rapscallion", "sycophant", "vagabond",
    "wanderlust", "xerophyte", "yuletide", "zenith", "abecedarian",
    "galvanize", "quagmire", "kleptomaniac", "logomachy", "paradoxical",
    "sacrosanct", "taciturn", "vivacious", "abstemious", "malfeasance",
    "capricious", "indomitable", "nebulous", "paraphernalia", "serendipity",
    "antidisestablishmentarianism", "bibliopole", "chrysanthemum", "doppelganger", "ephemeral",
    "fainthearted", "grandiloquent", "hullabaloo", "insouciant", "jocularity",
    "kaleidoscopic", "loquacious", "mellifluous", "nonchalant", "obstreperous",
    "pulchritudinous", "quizzically", "reminiscence", "sycamore", "transcendental",
    "ubiquitously", "vexatiously", "whimsically", "xenophobically", "youthfulness",
    "zealously", "abstemiously", "bouillabaisses", "cryptographers", "dodecahedrons",
    "equinoctials", "floccinaucinihilipilifications", "gobbledygook", "hyperventilating", "incomprehensibilities",
    "jackanapes", "kaleidoscopically", "lackadaisicalness", "magnanimousness", "nondescriptiveness"
]