words = [
    "Abacus", "Abbey", "Abundant", "Academic", "Accordion", "Acrobat", "Admiral", "Aerial", 
    "Agriculture", "Algorithm", "Alley", "Alloy", "Alphabet", "Amber", "Ambush", "Anatomy", 
    "Angelic", "Antique", "Apartment", "Apothecary", "Archery", "Armada", "Aromatic", 
    "Artisan", "Aspiration", "Atmosphere", "Auction", "Avalanche", "Aviary", "Azure", 
    "Bakery", "Ballad", "Banquet", "Baroque", "Bazaar", "Beehive", "Begonia", "Beloved", 
    "Beverage", "Bibliophile", "Biscuit", "Blazing", "Blossom", "Blueprint", "Blunder", 
    "Bonfire", "Botanical", "Boulevard", "Bracelet", "Bravery", "Breathtaking", "Bungalow", 
    "Butterfly", "Cabaret", "Cabbage", "Cadence", "Calamity", "Caliber", "Camaraderie", 
    "Candlelight", "Canvas", "Carnival", "Cascade", "Cathedral", "Celestial", "Ceramic", 
    "Chandelier", "Chaplain", "Charming", "Chemistry", "Chestnut", "Chivalry", "Chrysanthemum", 
    "Cinnamon", "Civilization", "Clarity", "Clavichord", "Clementine", "Clockwork", 
    "Clover", "Coastal", "Coconut", "Collage", "Colonial", "Comet", "Compass", "Confectionery", 
    "Constellation", "Contemporary", "Coral", "Cosmic", "Countryside", "Courage", "Cradle", 
    "Cranberry", "Crimson", "Crystalline", "Culinary", "Cupcake", "Curiosity", "Cypress", 
    "Daffodil", "Dandelion", "Dashing", "Dawn", "Daybreak", "Delightful", "Demure", 
    "Desert", "Desirable", "Destiny", "Diamond", "Dignity", "Dolphin", "Dormitory", 
    "Dragonfly", "Dramatic", "Dreamlike", "Driftwood", "Eagle", "Eccentric", "Eclipse", 
    "Ecosystem", "Eloquent", "Ember", "Emerald", "Emissary", "Enchanting", "Endeavor", 
    "Energy", "Enigmatic", "Epidemic", "Epiphany", "Equinox", "Ethereal", "Euphoric", 
    "Evergreen", "Exquisite", "Extravaganza", "Fable", "Fabric", "Fabulous", "Fairytale", 
    "Fascination", "Feather", "Festival", "Fiesta", "Firefly", "Flamboyant", "Flannel", 
    "Flourish", "Foxtrot", "Fragile", "Freestyle", "Frosty", "Galaxy", "Gallant", 
    "Gardenia", "Garland", "Gemstone", "Gentleman", "Gingerbread", "Giraffe", "Gladiator", 
    "Gleaming", "Glorious", "Gondola", "Gorgeous", "Gossamer", "Grandiose", "Grapevine", 
    "Grotto", "Harmony", "Hazelnut", "Heirloom", "Helium", "Herald", "Hibernation", 
    "Himalayan", "Hologram", "Honeycomb", "Horizon", "Hospitality", "Hummingbird", 
    "Illumination", "Imagine", "Immaculate", "Imperial", "Incandescent", "Indigo", 
    "Infinity", "Influential", "Ingenious", "Inspiration", "Intellect", "Iridescent", 
    "Jasmine", "Jubilee", "Judicious", "Junction", "Jurassic", "Kaleidoscope", "Kangaroo", 
    "Keepsake", "Kestrel", "Kilimanjaro", "Labyrinth", "Lacework", "Lakeside", "Laughter", 
    "Lavender", "Legendary", "Lighthouse", "Limerick", "Luminous", "Lyric", "Magnolia", 
    "Majestic", "Mandolin", "Marigold", "Marvelous", "Meadow", "Melody", "Meteor", 
    "Midnight", "Miraculous", "Mistletoe", "Moonlight", "Mosaic", "Mountainous", "Mysterious", 
    "Nautical", "Nebula", "Neon", "Nightingale", "Nostalgia", "Novelty", "Nymph", 
    "Oasis", "Obsidian", "Odyssey", "Olive", "Opal", "Oracle", "Orchid", "Overture", 
    "Pacific", "Palisade", "Panorama", "Paradise", "Paragon", "Parliament", "Passionate", 
    "Pavillion", "Peacock", "Pegasus", "Peninsula", "Perennial", "Phantom", "Phoenix", 
    "Pineapple", "Pioneer", "Pistachio", "Platinum", "Plaza", "Pleiades", "Polaris", 
    "Porcelain", "Prairie", "Precious", "Pristine", "Prowess", "Quasar", "Quest", 
    "Quintessential", "Radiant", "Rainbow", "Rapture", "Renaissance", "Reverie", "Rhapsody", 
    "Ribbon", "Richness", "Ripple", "Riverside", "Rosary", "Rosewood", "Sacred", 
    "Safari", "Sapphire", "Scarlet", "Seaside", "Serenade", "Serenity", "Shimmer", 
    "Silhouette", "Silver", "Solstice", "Sonata", "Sorcery", "Southern", "Spectrum", 
    "Spices", "Splendid", "Sprinkle", "Starlight", "Stately", "Steadfast", "Stellar", 
    "Stratosphere", "Streamline", "Subtle", "Summit", "Sunflower", "Sunrise", "Sunset", 
    "Surreal", "Symphony", "Tangerine", "Tapestry", "Tenderness", "Terrestrial", "Thistle", 
    "Thrilling", "Timeless", "Titanium", "Topaz", "Tranquil", "Treasure", "Tropical", 
    "Tulip", "Twilight", "Umbrella", "Unicorn", "Uplift", "Valiant", "Vanilla", 
    "Velvet", "Verdant", "Vibrant", "Victory", "Vineyard", "Vintage", "Visionary", 
    "Vivid", "Voyage", "Walnut", "Wanderlust", "Wavelength", "Whimsical", "Whisper", 
    "Wildflower", "Windmill", "Wisteria", "Wonderland", "Zephyr", "Zodiac", "Zoology"
]